package:
  name: julia
  version: 0.5.2

source:
  fn: julia-0.5.0-linux-x86_64.tar.gz # [linux64]
  url: https://julialang.s3.amazonaws.com/bin/linux/x64/0.5/julia-0.5.0-linux-x86_64.tar.gz # [linux64]

build:
  binary_relocation: False

test:
  files:
    - run_test.jl
  commands:
    - which julia
    - julia --version
    - julia --check-bounds=yes run_test.jl

about:
  home: http://julialang.org
  license_file: LICENSE.md
