package:
  name: julia
  version: 0.5.0

source:
  fn: julia-0.5.0-linux-x86_64.tar.gz # [linux64]
  fn: julia-0.5.0-linux-arm.tar.gz    # [linux32]
  url: https://julialang.s3.amazonaws.com/bin/linux/x64/0.5/julia-0.5.0-linux-x86_64.tar.gz # [linux64]
  url: https://julialang.s3.amazonaws.com/bin/linux/arm/0.5/julia-0.5.0-linux-arm.tar.gz   # [linux32]
  md5: 40563b7b116d76f052c3f0859608655d # [linux64]
  md5: 4dfeaef0c9815be7d5a544e0ee9486f9 # [linux32]
  # from https://s3.amazonaws.com/julialang/bin/checksums/julia-0.5.0.md5

build:
  binary_relocation: False

test:
  files:
    - run_test.jl
  commands:
    - which julia
    - julia --version
    - julia --check-bounds=yes run_test.jl

about:
  home: http://julialang.org
  license_file: LICENSE.md
